### ISSUE TITLE
Typo in the documentation of type65_https.pl

### ISSUE THREAD

**Issue by bortzmeyer** [massar/misc#1]
` misc/type65_https/type65_https.pl` says:

```
# perl type65_https.pl 'example.org HTTPS example.net'
```

Priority is mandatory so it should be ` # perl type65_https.pl 'example.org HTTPS 0 example.net'`. Otherwise:

```
Argument "www.bortzmeyer.org" isn't numeric in integer addition (+) at /usr/share/perl5/vendor_perl/Net/DNS/RR/SVCB.pm line 166.
domain identifier undefined at /usr/share/perl5/vendor_perl/Net/DNS/RR/SVCB.pm line 174.
in Net::DNS::RR->new( bortzmeyer.org HTTPS www.bortzmeyer.org )
 at type65_https.pl line 30.
```

**Comment by massar** [comment]
Hi @bortzmeyer,

Thanks for noticing and reporting. I have committed https://github.com/massar/misc/commit/a90d6a09107d486f6c9ebb2e42906cbdc31fffcc to resolve this.

Regards,
 Jeroen
